databases:
  - name: condotools-db
    plan: free

services:
  - type: web
    name: condotools-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: condotools-db
          property: connectionString
      - key: CORS_ALLOWED_ORIGINS
        value: https://condotools-frontend.onrender.com
      - key: RENDER_EXTERNAL_HOSTNAME
        fromService:
          type: web
          name: condotools-backend
          property: host
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production

  - type: web
    name: condotools-frontend
    env: static
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://condotools-backend.onrender.com/api
